on: [push]
name: Azure ARM
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: "08c8e939-d43d-4e15-b61e-a6ec4a1a3c43"
        tenant-id: "16b3c013-d300-468d-ac64-7eda0820b6d3"
        subscription-id: "93dab153-f48b-4313-b1dc-fb834325ad6e"

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "93dab153-f48b-4313-b1dc-fb834325ad6e"
        resourceGroupName: "azbkdemo-rg"
        template: ./main.bicep
        parameters: 'storagePrefix=mystore storageSKU=Standard_LRS'
        failOnStdErr: false
